baseURL = "http://example.org/"
languageCode = "en-us"
title = "Build a Static Website on AWS Amplify"
theme = "hugo-theme-learn"
uglyurls = true
relativeURLs = true

[params]
themeVariant = "mine"
showVisitedLinks = true
author = "Jenna Pederson"
description = "Build a Static Website on AWS Amplify"
disableSearch = true
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @jennapederson"
identifier = "tw"
url = "https://twitter.com/intent/user?screen_name=jennapederson"
weight = 1
