baseURL = "http://example.org/"
languageCode = "en-us"
title = "Build a Static Website on AWS Amplify"
theme = "hugo-theme-learn"
uglyurls = true

[params]
themeVariant = "mine"
showVisitedLinks = true
author = "Jenna Pederson"
description = "Build a Static Website on AWS Amplify"
disableSearch = true
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true